[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "slot-calculator"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[lints]
workspace = true

[dependencies]
clap        = { workspace = true, features = ["derive", "help"] }
hex-literal = { workspace = true }
sha2        = { workspace = true }
sha3        = { workspace = true }
slotlib     = { workspace = true }
typed-arena = "2.0"
unionlabs   = { workspace = true, features = ["rlp"] }
